server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/pokemon-db
    username: poke-user
    password: pokemondb2020_.
    
logging:
  level:
    org:
      hibernate:
        SQL: debug
